### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by H1PnOT1C** [nathan78906/steam-salien-cheat#12]
https://s5.postimg.cc/6uryju5ef/Screenshot_2018-06-30-11-33-59.png

**Comment by jsetoain** [comment]
It's a missing key in one of the zones. You can make a quick fix replacing line 50:

`if zone["type"] == 3 and zone["capture_progress"] < 0.9 and zone["capture_progress"] != 0:
`
with:

`if zone["type"] == 3 and "capture_progress" in zone and zone["capture_progress"] < 0.9 and zone["capture_progress"] != 0:`

**Comment by H1PnOT1C** [comment]
It works now, thank you very much
