### ISSUE TITLE
Checking if user is currently on a planet | Finding a planet and zone | 'capture_progress'

### ISSUE THREAD

**Issue by vfjpl** [nathan78906/steam-salien-cheat#13]
![](https://s5.postimg.cc/6uryju5ef/Screenshot_2018-06-30-11-33-59.png)

More info:
https://github.com/nathan78906/steam-salien-cheat/issues/12

**Comment by BeauTaapken** [comment]
you have to replace line 50 with the following code:

if zone["type"] == 3 and "capture_progress" in zone and zone["capture_progress"] < 0.9 and zone["capture_progress"] != 0:
