### ISSUE TITLE
Heroku App/Account Suspensions

### ISSUE THREAD

**Issue by nathan78906** [nathan78906/steam-salien-cheat#15]
Let me know if any of your Heroku apps/accounts have been suspended because of running this script. Seems like a lot of people using other scripts have been getting "caught" by Heroku. I've tried to follow their TOS as much as possible to prevent this.

**Comment by ChthonicOne** [comment]
What is Heroku and why do they care about this script?

**Comment by nathan78906** [comment]
Heroku is a free service that allows you to run apps in the "cloud" 24/7. Me(along with some others) are running it on Heroku 24/7 so that we don't need to keep our computers on 24/7.

**Comment by ChthonicOne** [comment]
Not running computer 24/7? Does not compute.

**Comment by cenkpurtas1** [comment]
While running other scripts, the reason for ban was "We detected that one of your applications violates Prohibited Action 2 of our Acceptable Use Policy (abusive, fraudulent, infringing)".  I don't think they allow this script neither.

**Comment by SakhJack** [comment]
Can you make brief guide how to run it on Heroku
I deployed repo but there are files missing to use features like logs, configs, turn on/off etc

**Comment by GitSeal** [comment]
@nathan78906  
how to add multiple token using heroku in 1 app

**Comment by nathan78906** [comment]
@GitSeal 
Duplicate the `saliens.py` and change the token/steamid, name it something like `saliens2.py`.

Then, in your "Procfile", add `worker2: python saliens2.py` to the file(on a new line). 
Start the worker the same way you did for the first worker.

**Comment by Jonahgay** [comment]
How many workers can i put until it brcomes payable ?

**Comment by nathan78906** [comment]
@Jonahgay 
Each worker takes up 24 dyno hours per day. Since its a new month, you should have 500 dyno hours (or 1000 if you added a credit card). Since the game ends on July 4th, you should be able to run 10 workers (or 20 if you added a credit card)

**Comment by ghost** [comment]
Also, how to update the saliens.py in Heroku

**Comment by nathan78906** [comment]
@Jonahgay 
Re-copy over the updated script (and input the token/steamid), commit/push the files to github. Then go back to the "Deploy" tab on Heroku, and click "Deploy Branch" 

![image](https://user-images.githubusercontent.com/24365131/42190222-edd231c2-7e29-11e8-89f6-12546ae00df1.png)

**Comment by AcTePuKc** [comment]
I'm getting this error - Getting user info errored... trying again(after 10s cooldown)
Any suggestions ?

**Comment by nathan78906** [comment]
@AcTePuKc 
You probably didnt input your token into the script properly.

**Comment by nathan78906** [comment]
Game over, thanks everyone 👍
