### ISSUE TITLE
Boss problem

### ISSUE THREAD

**Issue by H1PnOT1C** [nathan78906/steam-salien-cheat#17]
http://i.imgur.com/JUasEVA.jpg

**Comment by nathan78906** [comment]
Steam API bugged out, script should retry from the start after 3-4 report boss score errors. 

![image](https://user-images.githubusercontent.com/24365131/42131559-97901746-7cd2-11e8-9375-c1abdc9be4c3.png)

**Comment by vfjpl** [comment]
There seams to be a problem if you don't put your STEAMID into script. I just checked the logs and I coudn't join any boss during the night :<

**Comment by nathan78906** [comment]
Inputting steamid only affects the printing of the boss info during the game, you should still be able to do everything else. The following is the only place the steamid is used (to display your personalized boss progress) 
``
STEAM3ID = steam64_to_steam3(STEAMID)
                if player["accountid"] == STEAM3ID or STEAM3ID == "":
                    print("Name: {} | HP: {}/{} | XP Earned: {}".format(
                        player["name"],
                        player["hp"],
                        player["max_hp"],
                        player["xp_earned"]))
``
(sorry for formatting)

**Comment by nathan78906** [comment]
You're right, theres an error when the script looks for the variable set to "" (empty).

Will fix in the morning.

**Comment by H1PnOT1C** [comment]
My ID is in script, just to be sure, the ID should be this https://steamcommunity.com/id/H1PnOT1C or just H1PnOT1C ?

**Comment by nathan78906** [comment]
No, its the long number you get from https://steamcommunity.com/saliengame/gettoken

The number is in the "steamid" tag when you visit that page (while logged in)

**Comment by vfjpl** [comment]
The "int(empty)" bug is not the only one. Did you manage to connect to boss fight without steamid in script?

**Comment by nathan78906** [comment]
You should be able to connect without any problems, steamid is only used for filtering output during the boss fight. If no steamid is given (set to "") then it will print the HP/EXP for all players in your group for the boss fight.

**Comment by vfjpl** [comment]
Ok. I will test on the next boss. I think int(empyt) error was messing with connection because as soon as i put steamid I was able to connect to boss. Before it was not possible.

**Comment by vfjpl** [comment]
Seems ok. It's now connect correctly.
