### ISSUE TITLE
Is boss score reporting working or no?

### ISSUE THREAD

**Issue by Hooli12** [nathan78906/steam-salien-cheat#19]
![snip_20180701143326](https://user-images.githubusercontent.com/40499939/42134094-2effc6a2-7d3d-11e8-92d5-ce1ccf1824cf.png)
Uploaded pic

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Everything is alright, the first 5-6 ticks after you join or rejoin are always 0.

**Comment by nathan78906** [comment]
The first few XP Gained responses will return 0 because the game is in a state of "waiting for players" to join your group

**Comment by LoneDev6** [comment]
Is it 772.500 EXP earned with boss battle low or normal? Thanks

**Comment by nathan78906** [comment]
Thats normal, you may have been getting more XP with previous bosses but that's because they were spawned less frequently. They've made some changes to increaae boss frequency but lower the amount of XP you get per boss.

**Comment by LoneDev6** [comment]
Oh I see, thanks a lot! We can close the issue I think
