### ISSUE TITLE
Game does not detect boss zones properly

### ISSUE THREAD

**Issue by ChthonicOne** [nathan78906/steam-salien-cheat#8]
The boss zones started spawning and the program doesn't properly detect them and go to them, instead wasting time at level 1 zones.

**Comment by nathan78906** [comment]
I already implemented it, currently testing.

**Comment by ChthonicOne** [comment]
If it's safe for use, you could branch it and i'll help test it.

I was looking into what needs to be done to fix it, but I don't know their API. Instead I was looking into other cheats hoping they did something.

**Comment by nathan78906** [comment]
Check out the `boss` branch, currently waiting for this boss game to finish before I merge to `master`

![image](https://user-images.githubusercontent.com/24365131/42120259-9735f550-7be6-11e8-8dbc-19e0b995c4d6.png)

**Comment by ChthonicOne** [comment]
I'm adding a check for my name and avoiding the spam ;)

**Comment by nathan78906** [comment]
Seems to have worked, I jumped from Level 16 to Level 19 with that boss zone

**Comment by ChthonicOne** [comment]
I only got 450k since I joined late, but yeah, it works.

**Comment by ChthonicOne** [comment]
I put a check in the game to check for my name and only print that one out. Might want to consider something similar for others.

**Comment by nathan78906** [comment]
Testing the filtering on boss output, requires users to get their "accountid" from https://steam3id.com and input it in the script. (Also if they don't add it, it will just print everything as before)

(see latest commit in boss branch)

**Comment by ChthonicOne** [comment]
Thanks, it's a little more elegant than mine. I just had it check for my name specifically ;)
